
[ClassVersion("1.0.0.0"), FriendlyName("SecurityTemplate")]
class MSFT_SecurityTemplate : OMI_BaseResource
{
    [Key, Description("The path to the desired security policy template (.inf)")] String Path;
};

